### ISSUE TITLE
Etusivun kuvat eivät centeröidy

### ISSUE THREAD

**Issue by StinaSoile** [StinaSoile/matikkasarjis#2]
sarjiksien kansikuvat etusivullla pysyvät vasemmassa reunassa.  No big deal mutta helppo korjata.

**Comment by sepi4** [comment]
![image](https://github.com/user-attachments/assets/fc224d69-74b8-41c9-97fd-a3304959b19b)

**Comment by sepi4** [comment]
![image](https://github.com/user-attachments/assets/509b920b-8ad1-4b28-91cb-4100d9ef01e3)
