### ISSUE TITLE
Feature: kysymykset ja vastausboksit sarjakuvasivujen yhteyteen

### ISSUE THREAD

**Issue by StinaSoile** [StinaSoile/matikkasarjis#7]
- kysymys- ja vastaus-formin visuaalinen ilme täytyy kokonaan pohtia ja toteuttaa, ks. kuva 1

![image](https://github.com/user-attachments/assets/68aa2239-8a31-4f7d-b1d6-8d8ac5ad1e0a)

- ks. kuva 2.  comicData.js - filessa on taulukko jokaiseen sarjakuvaan liittyen. Siinä on jokaiseen sarjakuvasivuun liittyen mahdollisia kysymyksiä ja vastauksia. Tarkoitus on lukea tätä taulukkoa ja renderöidä sarjakuvasivun alaosaan  sen perusteella 
0 - n kpl kysymyksiä, vastauslaatikot jokaiselle, sekä jollain tapaa huomioida (esim console.log-tasolla), jos vastauskenttään kirjoitetaan taulukon oikean vastauksen mukainen vastaus. 
- Ei ole vielä ajankohtaista saada mitään järkevää toimintaa tapahtumaan oikeasta vastauksesta.
- taulukko ei varmastikaan ole paras muoto datalle, joten pitää keksiä parempi jos tarvii.
![image](https://github.com/user-attachments/assets/3735f944-ea1c-4385-9fb1-390c5f6baf6f)

**Comment by sepi4** [comment]
ehkä kannattaa laittaa jotain muuta kun `string[][]`
pages rakenteeksi

ehkä esim.
```ts
type P = {
  image: string,
  questions?: Q[]
}
type Q = {
  question: string,
  answer: string,
}
```
